baseurl = "https://eumedemito.net/"
title = "Eu Me Demito"
author = "e-L396A"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

defaultContentLanguage = "pt-br"

[params]
  disableWebFonts = false
  hyvorTalkID = 7175

  [params.footer]
    copyright = "Copyright © 2022 e-L396A"
    email = "e-L396A@proton.me"

[[menu.main]]
    name = "Sobre"
    url  = "/sobre"
    params = { title  = "Saiba mais sobre este blog" }

[[menu.main]]
    name = "RSS"
    url  = "/index.xml"
    params = { title  = "RSS feed (todos artigos do blog)" }
